;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        counsel-M-x
        crux-move-beginning-of-line
        electric-newline-and-maybe-indent
        forward-sentence
        indent-for-tab-command
        kill-region
        org-yank
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/body
        hydra-multiple-cursors/ignore
        hydra-multiple-cursors/mc/add-cursor-on-click
        hydra-multiple-cursors/mc/edit-lines-and-exit
        hydra-multiple-cursors/mc/insert-letters-and-exit
        hydra-multiple-cursors/mc/insert-numbers-and-exit
        hydra-multiple-cursors/mc/mark-all-like-this-and-exit
        hydra-multiple-cursors/mc/mark-next-like-this
        hydra-multiple-cursors/mc/mark-previous-like-this
        hydra-multiple-cursors/mc/skip-to-next-like-this
        hydra-multiple-cursors/mc/skip-to-previous-like-this
        hydra-multiple-cursors/mc/unmark-next-like-this
        hydra-multiple-cursors/mc/unmark-previous-like-this
        hydra-multiple-cursors/nil
        ))
